// utils/assignCategory.js

/**
 * Given a full description string, returns a suggested category name.
 * If no keyword is found, returns "Uncategorized".
 */
function assignCategory(fullDescription) {
  if (!fullDescription || typeof fullDescription !== "string") {
    return "Uncategorized";
  }

  const desc = fullDescription.toLowerCase();

  // Category definitions ordered by checking priority
  const categories = {
    // Highest priority categories (specific matches)
    "Rent/Mortgage": [
      "apartment",
      "rent",
      "mortgage",
      "homestead",
      "leasing",
      "dwell",
      "property management",
      "realty",
      "landlord",
    ],
    Utilities: [
      "electric",
      "water",
      "gas bill",
      "sewer",
      "trash",
      "recycling",
      "pge",
      "comcast",
      "verizon",
      "at&t",
      "xcel energy",
      "duke energy",
      "internet",
      "utility",
      "power",
      "electricity",
      "gas & electric",
    ],
    Insurance: [
      "geico",
      "statefarm",
      "allstate",
      "progressive",
      "aaa insurance",
      "health insurance",
      "car insurance",
      "life insurance",
      "aetna",
      "unitedhealth",
      "bluecross",
      "flood insurance",
    ],
    Subscriptions: [
      "netflix",
      "spotify",
      "youtube premium",
      "amazon prime",
      "hulu",
      "disney+",
      "apple tv",
      "apple music",
      "patreon",
      "medium membership",
      "new york times",
      "wsj",
      "audible",
      "adobe",
      "microsoft 365",
      "dropbox",
      "icloud",
      "slack",
      "zoom",
      "linkedin premium",
      "openai",
      "chatgpt",
    ],

    // Common daily expenses
    Groceries: [
      "safeway",
      "whole foods",
      "aldi",
      "trader joe",
      "kroger",
      "publix",
      "costco",
      "walmart grocery",
      "heb",
      "wegmans",
      "food lion",
      "99 ranch",
      "hmart",
      "meijer",
      "giant eagle",
      "shoprite",
      "stater bros",
      "save mart",
      "grocery",
      "supermarket",
      "dillons",
      "hy-vee",
      "winco",
    ],
    Restaurants: [
      "mcdonald",
      "burger king",
      "subway",
      "starbucks",
      "taco bell",
      "chipotle",
      "pizza hut",
      "domino",
      "panera",
      "dunkin",
      "chick-fil-a",
      "wendy",
      "kfc",
      "olive garden",
      "applebees",
      "buffalo wild wings",
      "panda express",
      "cafe",
      "restaurant",
      "grubhub",
      "ubereats",
      "doordash",
      "postmates",
      "takeout",
      "diner",
      "brunch",
      "bakery",
    ],
    "Gas/Automotive": [
      "arco",
      "shell",
      "exxon",
      "chevron",
      "valero",
      "bp",
      "76 station",
      "costco gas",
      "quik trip",
      "7-eleven",
      "gas station",
      "tire",
      "auto repair",
      "jiffy lube",
      "mechanic",
      "car wash",
      "oil change",
      "smog check",
      "autozone",
      "pep boys",
      "dealership",
      "tesla charger",
    ],
    Transportation: [
      "uber",
      "lyft",
      "taxi",
      "amtrak",
      "bart",
      "mta",
      "metro",
      "public transit",
      "toll",
      "ez-pass",
      "fastrak",
      "lyft",
      "greyhound",
      "airport",
      "parking",
      "meter",
      "dash",
      "gasolina",
      "fuel",
      "petrol",
      "clipper",
    ],

    // Less frequent but significant expenses
    Healthcare: [
      "cvs",
      "walgreens",
      "rite aid",
      "pharmacy",
      "hospital",
      "clinic",
      "dental",
      "optometrist",
      "eye doctor",
      "physician",
      "copay",
      "prescription",
      "urgent care",
      "labcorp",
      "quest diagnostics",
      "kaiser",
      "medical",
      "therapy",
      "psychiatrist",
      "vitamin",
    ],
    Entertainment: [
      "movie",
      "cinema",
      "amc",
      "regal",
      "concert",
      "ticketmaster",
      "stubhub",
      "bowling",
      "golf",
      "arcade",
      "museum",
      "zoo",
      "aquarium",
      "theme park",
      "netflix",
      "hulu",
      "spotify",
      "video game",
      "steam",
      "playstation",
      "xbox",
      "nintendo",
    ],
    Shopping: [
      "amazon",
      "ebay",
      "target",
      "walmart",
      "best buy",
      "home depot",
      "lowes",
      "ikea",
      "nordstrom",
      "macy",
      "kohl",
      "sephora",
      "zara",
      "h&m",
      "forever 21",
      "gap",
      "old navy",
      "etsy",
      "apple store",
      "google store",
      "booking",
      "reservation",
    ],
    Travel: [
      "airbnb",
      "hotel",
      "marriott",
      "hilton",
      "expedia",
      "kayak",
      "delta",
      "united airline",
      "american airline",
      "southwest",
      "jetblue",
      "spirit",
      "orbitz",
      "priceline",
      "hostel",
      "resort",
      "cruise",
      "travelocity",
      "tripadvisor",
      "visa fee",
    ],

    // Financial obligations
    "Fees & Charges": [
      "atm fee",
      "service charge",
      "late fee",
      "overdraft",
      "maintenance fee",
      "wire transfer",
      "convenience fee",
      "transaction fee",
      "shipping",
      "handling",
      "taxes",
      "license fee",
      "registration",
      "postage",
      "notary",
    ],

    // Personal development
    Education: [
      "coursera",
      "udemy",
      "edx",
      "skillshare",
      "masterclass",
      "textbook",
      "university",
      "college",
      "tuition",
      "student loan",
      "khan academy",
      "codecademy",
      "duolingo",
      "training",
      "seminar",
      "workshop",
      "certification",
      "parchment",
      "college transcripts",
    ],

    // Miscellaneous
    "Gifts/Donations": [
      "donation",
      "charity",
      "goodwill",
      "salvation army",
      "red cross",
      "unicef",
      "gofundme",
      "kickstarter",
      "patreon",
      "birthday gift",
      "wedding gift",
      "tip",
      "church",
      "tithe",
      "offering",
      "fundraiser",
    ],
    Kids: [
      "diapers",
      "formula",
      "toys r us",
      "baby gap",
      "carters",
      "daycare",
      "preschool",
      "tutoring",
      "pediatrician",
      "babysitter",
      "swim lessons",
      "kindercare",
      "kumon",
      "lego",
      "stroller",
    ],
    Pets: [
      "petco",
      "petsmart",
      "vet",
      "veterinarian",
      "chewy",
      "boarding",
      "grooming",
      "dog food",
      "cat food",
      "frisco",
      "blue buffalo",
      "purina",
      "ark naturals",
    ],
  };

  // Check categories in priority order
  for (const [category, keywords] of Object.entries(categories)) {
    for (const keyword of keywords) {
      if (desc.includes(keyword)) return category;
    }
  }
  // If no match, return default category
  return "Uncategorized";
}

module.exports = assignCategory;
